FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app



FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TiklaGelsinAPI/TiklaGelsinAPI.csproj", "TiklaGelsinAPI/"]
RUN dotnet restore "TiklaGelsinAPI/TiklaGelsinAPI.csproj"
COPY . .
WORKDIR "/src/TiklaGelsinAPI"
RUN dotnet build "TiklaGelsinAPI.csproj" -c Release -o /app/build


FROM build AS publish
RUN dotnet publish "TiklaGelsinAPI.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
EXPOSE 80
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TiklaGelsinAPI.dll"]